---
- name: Destroy debug
  hosts: all
  become: yes
  gather_facts: no

  pre_tasks:
    - name: Wait for system to become reachable
      wait_for_connection:
        delay: 10
        timeout: 120

    - name: Wait for cloud-init to complete
      command: cloud-init status --wait
      changed_when: false
      become: yes
      ignore_errors: yes

    - name: Gather facts after waiting
      setup:

  tasks:
    - name: Afficher le message de debug
      ansible.builtin.debug:
        msg: "coucou update"